name: live

on:
  schedule:
    - cron: '7,22,37,52 13-22 * * *'
      timezone: 'Asia/Tokyo'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yml
    with:
      live: true
